package fcatools.conexpng;

public enum ContextChangeEvents {
    CANCELCALCULATIONS, CONTEXTCHANGED, ATTRIBUTENAMECHANGED, NEWCONTEXT, LABELSCHANGED, STARTCALCULATION, ENDCALCULATION, TEMPORARYCONTEXTCHANGED, NEWLATTICE, LOADEDFILE,
 // (F1) AJOUTE CET ÉVÉNEMENT :
    LATTICECHANGED  // Pour notifier les changements de groupe du treillis;
}
